version: '3.8'

services:
  mountpoint-s3-demo:
    extends:
      file: compose.yml
      service: mountpoint-s3
    build:
      context: .
      target: demo
    image: ghcr.io/diagraphics/mountpoint-s3:demo
    command: ["pub", "/mnt/pub"]
    ports:
      - "8080:8080"
