services:
  mountpoint-s3:
    build: .
    image: ghcr.io/diagraphics/mountpoint-s3:dev
    privileged: true
    ports:
      - "8080:80"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - AWS_REGION
      - MOUNTPOINT_BUCKETS
      - MOUNTPOINT_PREFIX
      - MOUNTPOINT_LOG
