version: '3.8'
services:
  mountpoint-s3:
    build: .
    image: ghcr.io/diagraphics/mountpoint-s3:dev
    privileged: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - AWS_ENDPOINT_URL_S3
      - AWS_REGION
      - AWS_S3_FORCE_PATH_STYLE=true
      - MOUNTPOINT_LOG
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_SIGV4A_SIGNING_REGION_SET=us-east-1
    command: ["pub", "/mnt/pub"]
