#! /usr/bin/env -S node --no-warnings=ExperimentalWarning

import * as esbuild from "esbuild";

await esbuild.build({
  entryPoints: ["src/sign.ts"],
  logLevel: "info",
  outdir: "dist",
  bundle: true,
  format: "esm",
  platform: "node",
//   packages: "bundle",
  tsconfig: "tsconfig.json",
});
